'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DsSanBayTrungGian
    Inherits DataSet
    
    Private tableChiTietChuyenBay As ChiTietChuyenBayDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("ChiTietChuyenBay")) Is Nothing) Then
                Me.Tables.Add(New ChiTietChuyenBayDataTable(ds.Tables("ChiTietChuyenBay")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property ChiTietChuyenBay As ChiTietChuyenBayDataTable
        Get
            Return Me.tableChiTietChuyenBay
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DsSanBayTrungGian = CType(MyBase.Clone,DsSanBayTrungGian)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("ChiTietChuyenBay")) Is Nothing) Then
            Me.Tables.Add(New ChiTietChuyenBayDataTable(ds.Tables("ChiTietChuyenBay")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableChiTietChuyenBay = CType(Me.Tables("ChiTietChuyenBay"),ChiTietChuyenBayDataTable)
        If (Not (Me.tableChiTietChuyenBay) Is Nothing) Then
            Me.tableChiTietChuyenBay.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DsSanBayTrungGian"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DsSanBayTrungGian.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableChiTietChuyenBay = New ChiTietChuyenBayDataTable
        Me.Tables.Add(Me.tableChiTietChuyenBay)
    End Sub
    
    Private Function ShouldSerializeChiTietChuyenBay() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub ChiTietChuyenBayRowChangeEventHandler(ByVal sender As Object, ByVal e As ChiTietChuyenBayRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ChiTietChuyenBayDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnSanBayTrungGian As DataColumn
        
        Private columnThoiGianDung As DataColumn
        
        Private columnGhiChu As DataColumn
        
        Friend Sub New()
            MyBase.New("ChiTietChuyenBay")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property SanBayTrungGianColumn As DataColumn
            Get
                Return Me.columnSanBayTrungGian
            End Get
        End Property
        
        Friend ReadOnly Property ThoiGianDungColumn As DataColumn
            Get
                Return Me.columnThoiGianDung
            End Get
        End Property
        
        Friend ReadOnly Property GhiChuColumn As DataColumn
            Get
                Return Me.columnGhiChu
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As ChiTietChuyenBayRow
            Get
                Return CType(Me.Rows(index),ChiTietChuyenBayRow)
            End Get
        End Property
        
        Public Event ChiTietChuyenBayRowChanged As ChiTietChuyenBayRowChangeEventHandler
        
        Public Event ChiTietChuyenBayRowChanging As ChiTietChuyenBayRowChangeEventHandler
        
        Public Event ChiTietChuyenBayRowDeleted As ChiTietChuyenBayRowChangeEventHandler
        
        Public Event ChiTietChuyenBayRowDeleting As ChiTietChuyenBayRowChangeEventHandler
        
        Public Overloads Sub AddChiTietChuyenBayRow(ByVal row As ChiTietChuyenBayRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddChiTietChuyenBayRow(ByVal SanBayTrungGian As String, ByVal ThoiGianDung As Short, ByVal GhiChu As String) As ChiTietChuyenBayRow
            Dim rowChiTietChuyenBayRow As ChiTietChuyenBayRow = CType(Me.NewRow,ChiTietChuyenBayRow)
            rowChiTietChuyenBayRow.ItemArray = New Object() {SanBayTrungGian, ThoiGianDung, GhiChu}
            Me.Rows.Add(rowChiTietChuyenBayRow)
            Return rowChiTietChuyenBayRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As ChiTietChuyenBayDataTable = CType(MyBase.Clone,ChiTietChuyenBayDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New ChiTietChuyenBayDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnSanBayTrungGian = Me.Columns("SanBayTrungGian")
            Me.columnThoiGianDung = Me.Columns("ThoiGianDung")
            Me.columnGhiChu = Me.Columns("GhiChu")
        End Sub
        
        Private Sub InitClass()
            Me.columnSanBayTrungGian = New DataColumn("SanBayTrungGian", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSanBayTrungGian)
            Me.columnThoiGianDung = New DataColumn("ThoiGianDung", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnThoiGianDung)
            Me.columnGhiChu = New DataColumn("GhiChu", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnGhiChu)
        End Sub
        
        Public Function NewChiTietChuyenBayRow() As ChiTietChuyenBayRow
            Return CType(Me.NewRow,ChiTietChuyenBayRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New ChiTietChuyenBayRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(ChiTietChuyenBayRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.ChiTietChuyenBayRowChangedEvent) Is Nothing) Then
                RaiseEvent ChiTietChuyenBayRowChanged(Me, New ChiTietChuyenBayRowChangeEvent(CType(e.Row,ChiTietChuyenBayRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.ChiTietChuyenBayRowChangingEvent) Is Nothing) Then
                RaiseEvent ChiTietChuyenBayRowChanging(Me, New ChiTietChuyenBayRowChangeEvent(CType(e.Row,ChiTietChuyenBayRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.ChiTietChuyenBayRowDeletedEvent) Is Nothing) Then
                RaiseEvent ChiTietChuyenBayRowDeleted(Me, New ChiTietChuyenBayRowChangeEvent(CType(e.Row,ChiTietChuyenBayRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.ChiTietChuyenBayRowDeletingEvent) Is Nothing) Then
                RaiseEvent ChiTietChuyenBayRowDeleting(Me, New ChiTietChuyenBayRowChangeEvent(CType(e.Row,ChiTietChuyenBayRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveChiTietChuyenBayRow(ByVal row As ChiTietChuyenBayRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ChiTietChuyenBayRow
        Inherits DataRow
        
        Private tableChiTietChuyenBay As ChiTietChuyenBayDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableChiTietChuyenBay = CType(Me.Table,ChiTietChuyenBayDataTable)
        End Sub
        
        Public Property SanBayTrungGian As String
            Get
                Try 
                    Return CType(Me(Me.tableChiTietChuyenBay.SanBayTrungGianColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableChiTietChuyenBay.SanBayTrungGianColumn) = value
            End Set
        End Property
        
        Public Property ThoiGianDung As Short
            Get
                Try 
                    Return CType(Me(Me.tableChiTietChuyenBay.ThoiGianDungColumn),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableChiTietChuyenBay.ThoiGianDungColumn) = value
            End Set
        End Property
        
        Public Property GhiChu As String
            Get
                Try 
                    Return CType(Me(Me.tableChiTietChuyenBay.GhiChuColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableChiTietChuyenBay.GhiChuColumn) = value
            End Set
        End Property
        
        Public Function IsSanBayTrungGianNull() As Boolean
            Return Me.IsNull(Me.tableChiTietChuyenBay.SanBayTrungGianColumn)
        End Function
        
        Public Sub SetSanBayTrungGianNull()
            Me(Me.tableChiTietChuyenBay.SanBayTrungGianColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsThoiGianDungNull() As Boolean
            Return Me.IsNull(Me.tableChiTietChuyenBay.ThoiGianDungColumn)
        End Function
        
        Public Sub SetThoiGianDungNull()
            Me(Me.tableChiTietChuyenBay.ThoiGianDungColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsGhiChuNull() As Boolean
            Return Me.IsNull(Me.tableChiTietChuyenBay.GhiChuColumn)
        End Function
        
        Public Sub SetGhiChuNull()
            Me(Me.tableChiTietChuyenBay.GhiChuColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ChiTietChuyenBayRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As ChiTietChuyenBayRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As ChiTietChuyenBayRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As ChiTietChuyenBayRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
